"""Fixtures for tests."""

# killmails as received from the WS API
killmails_raw = {
    111519365: {
        "attackers": [
            {
                "damage_done": 34358,
                "faction_id": 500010,
                "final_blow": False,
                "security_status": 0,
                "ship_type_id": 209,
            },
            {
                "alliance_id": 1727758877,
                "character_id": 92837550,
                "corporation_id": 148763686,
                "damage_done": 6057,
                "final_blow": True,
                "security_status": 1.4,
                "ship_type_id": 17715,
                "weapon_type_id": 2185,
            },
            {
                "alliance_id": 1727758877,
                "character_id": 583637272,
                "corporation_id": 148763686,
                "damage_done": 4236,
                "final_blow": False,
                "security_status": 0.1,
                "ship_type_id": 22456,
                "weapon_type_id": 22456,
            },
        ],
        "killmail_id": 111519365,
        "killmail_time": "2023-09-08T17:18:46Z",
        "solar_system_id": 30001994,
        "victim": {
            "alliance_id": 99001317,
            "character_id": 2121345057,
            "corporation_id": 98520878,
            "damage_taken": 44651,
            "items": [
                {
                    "flag": 22,
                    "item_type_id": 24395,
                    "quantity_destroyed": 1,
                    "singleton": 0,
                },
                {
                    "flag": 11,
                    "item_type_id": 16375,
                    "quantity_dropped": 1,
                    "singleton": 0,
                },
                {
                    "flag": 5,
                    "item_type_id": 208,
                    "quantity_destroyed": 100,
                    "singleton": 0,
                },
                {
                    "flag": 5,
                    "item_type_id": 208,
                    "quantity_dropped": 100,
                    "singleton": 0,
                },
                {
                    "flag": 5,
                    "item_type_id": 15331,
                    "quantity_dropped": 11,
                    "singleton": 0,
                },
                {
                    "flag": 12,
                    "item_type_id": 4405,
                    "quantity_dropped": 1,
                    "singleton": 0,
                },
                {
                    "flag": 5,
                    "item_type_id": 213,
                    "quantity_destroyed": 200,
                    "singleton": 0,
                },
                {
                    "flag": 5,
                    "item_type_id": 5321,
                    "quantity_destroyed": 1,
                    "singleton": 0,
                },
                {
                    "flag": 5,
                    "item_type_id": 5339,
                    "quantity_destroyed": 2,
                    "singleton": 0,
                },
                {
                    "flag": 28,
                    "item_type_id": 23527,
                    "quantity_dropped": 1,
                    "singleton": 0,
                },
                {
                    "flag": 20,
                    "item_type_id": 24395,
                    "quantity_dropped": 1,
                    "singleton": 0,
                },
                {
                    "flag": 23,
                    "item_type_id": 6160,
                    "quantity_dropped": 1,
                    "singleton": 0,
                },
                {
                    "flag": 5,
                    "item_type_id": 35656,
                    "quantity_dropped": 1,
                    "singleton": 0,
                },
                {
                    "flag": 23,
                    "item_type_id": 29009,
                    "quantity_dropped": 1,
                    "singleton": 0,
                },
                {
                    "flag": 5,
                    "item_type_id": 7373,
                    "quantity_dropped": 1,
                    "singleton": 0,
                },
                {
                    "flag": 5,
                    "item_type_id": 8105,
                    "quantity_destroyed": 1,
                    "singleton": 0,
                },
                {
                    "flag": 21,
                    "item_type_id": 3504,
                    "quantity_destroyed": 1,
                    "singleton": 0,
                },
                {
                    "flag": 5,
                    "item_type_id": 6485,
                    "quantity_dropped": 2,
                    "singleton": 0,
                },
                {
                    "flag": 5,
                    "item_type_id": 20306,
                    "quantity_destroyed": 100,
                    "singleton": 0,
                },
                {
                    "flag": 14,
                    "item_type_id": 4405,
                    "quantity_dropped": 1,
                    "singleton": 0,
                },
                {
                    "flag": 5,
                    "item_type_id": 35660,
                    "quantity_destroyed": 1,
                    "singleton": 0,
                },
                {
                    "flag": 5,
                    "item_type_id": 217,
                    "quantity_destroyed": 100,
                    "singleton": 0,
                },
                {
                    "flag": 15,
                    "item_type_id": 3530,
                    "quantity_dropped": 1,
                    "singleton": 0,
                },
                {
                    "flag": 5,
                    "item_type_id": 223,
                    "quantity_dropped": 100,
                    "singleton": 0,
                },
                {
                    "flag": 94,
                    "item_type_id": 31047,
                    "quantity_destroyed": 1,
                    "singleton": 0,
                },
                {
                    "flag": 93,
                    "item_type_id": 31047,
                    "quantity_destroyed": 1,
                    "singleton": 0,
                },
                {
                    "flag": 5,
                    "item_type_id": 21867,
                    "quantity_dropped": 100,
                    "singleton": 0,
                },
                {
                    "flag": 13,
                    "item_type_id": 4405,
                    "quantity_dropped": 1,
                    "singleton": 0,
                },
                {
                    "flag": 5,
                    "item_type_id": 25711,
                    "quantity_dropped": 1,
                    "singleton": 0,
                },
                {
                    "flag": 27,
                    "item_type_id": 23527,
                    "quantity_dropped": 1,
                    "singleton": 0,
                },
                {
                    "flag": 5,
                    "item_type_id": 16515,
                    "quantity_dropped": 1,
                    "singleton": 0,
                },
                {
                    "flag": 87,
                    "item_type_id": 31876,
                    "quantity_dropped": 1,
                    "singleton": 0,
                },
                {
                    "flag": 5,
                    "item_type_id": 209,
                    "quantity_destroyed": 100,
                    "singleton": 0,
                },
                {
                    "flag": 92,
                    "item_type_id": 31035,
                    "quantity_destroyed": 1,
                    "singleton": 0,
                },
                {
                    "flag": 19,
                    "item_type_id": 35656,
                    "quantity_destroyed": 1,
                    "singleton": 0,
                },
                {
                    "flag": 16,
                    "item_type_id": 4403,
                    "quantity_dropped": 1,
                    "singleton": 0,
                },
                {
                    "flag": 5,
                    "item_type_id": 8115,
                    "quantity_dropped": 1,
                    "singleton": 0,
                },
                {
                    "flag": 5,
                    "item_type_id": 6437,
                    "quantity_dropped": 1,
                    "singleton": 0,
                },
                {
                    "flag": 29,
                    "item_type_id": 23527,
                    "quantity_destroyed": 1,
                    "singleton": 0,
                },
            ],
            "position": {
                "x": -1130555013314.7253,
                "y": -58789723184.4009,
                "z": 408626130437.3028,
            },
            "ship_type_id": 24700,
        },
        "zkb": {
            "locationID": 40127326,
            "hash": "84e4c1cb3d55389e213e34ebf3b9a1b0b6b3ac89",
            "fittedValue": 71946159.25,
            "droppedValue": 9739029.69,
            "destroyedValue": 65444018.61,
            "totalValue": 75183048.3,
            "points": 10,
            "npc": False,
            "solo": False,
            "awox": False,
            "esi": "https://esi.evetech.net/latest/killmails/111519365/84e4c1cb3d55389e213e34ebf3b9a1b0b6b3ac89/",
            "url": "https://zkillboard.com/kill/111519365/",
        },
    }
}
